spring:
  application:
    name: employee-service
#  config:
#    import: optional:configserver:http://config-cont:8888

  datasource:
    url: jdbc:mysql://localhost:3307/employee-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId: -}, %X{spanId: -}]'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8081