version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region {{AWS region}} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Log in to ECR successfully
      - aws ecr batch-delete-image --repository-name afarid-registry--image-ids imageTag=$IMAGE_TAG
  build:
    commands:
      - docker-compose --file=docker-compose.yml build
      - docker tag {{imageName1}}:latest {{AWS Account Id}}.dkr.ecr.{{AWS region}}.amazonaws.com/{{imageName1}}:latest
      - docker push {{AWS Account Id}}.dkr.ecr.{{AWS region}}.amazonaws.com/{{imageName1}}:latest
      - docker tag {{imageName2}}:latest {{AWS Account Id}}.dkr.ecr.{{AWS region}}.amazonaws.com/{{imageName2}}:latest
      - docker push {{AWS Account Id}}.dkr.ecr.{{AWS region}}.amazonaws.com/{{imageName2}}:latest