version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Logging into Amazon ECR started on `date`
      - aws --version
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 638038348168.dkr.ecr.eu-north-1.amazonaws.com
      - echo Setting repository URI...
      - REPOSITORY_URI=638038348168.dkr.ecr.eu-north-1.amazonaws.com/afarid-registry
      - echo $AWS_REGION
      - echo $IMAGE_TAG
      - aws ecr batch-delete-image --repository-name afarid-registry --image-ids imageTag=$IMAGE_TAG
  build:
    commands:
      - echo Build started at `date`
      - echo Building the docker image from docker-compose
      - docker-compose --file=docker-compose.yml build
      - docker tag image-1:latest 638038348168.dkr.ecr.$AWS_REGION.amazonaws.com/image-1:latest
      - docker push 638038348168.dkr.ecr.$AWS_REGION.amazonaws.com/image-1:latest