spring:
  datasource:
    url: jdbc:mysql://department-db-cont:3306/department-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry-cont:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8080

test:
  message: Hello today is Friday
