version: '3.7'
services:
  e_db:
    container_name: "employee-db-cont"
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "employee-db"
      MYSQL_USERNAME: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - '3307:3306'
    networks:
      - ms-db
networks:
  ms-db:
    driver: bridge