eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path= /api/v1/employees/**

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path= /api/v1/departments/**


server:
  port: 9191

logging:
  level:
    org:
      springframework:
        cloud:
         gateway:
           handler:
             RoutePredicateHandlerMapping: DEBUG
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId: -}, %X{spanId: -}]'
management:
  tracing:
    sampling:
      probability: 1