eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path= /api/v1/employees/**

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path= /api/v1/departments/**

server:
  port: 9191

logging:
  level:
    org:
      springframework:
        cloud:
         gateway:
           handler:
             RoutePredicateHandlerMapping: DEBUG